-- =============================================================================
-- Q Game - Seed data (auto-generated from src/data/questions.js)
-- =============================================================================
-- Paste this whole file into the Supabase SQL editor after running schema.sql.
-- Safe to re-run: ON CONFLICT (id) DO NOTHING means existing rows are kept.
--
-- Regenerate with: node scripts/generate-seed-sql.mjs
-- =============================================================================

begin;

insert into public.questions (id, category, text, tags, created_by) values
  ('wyr-001', 'Would You Rather', 'Would you rather be able to speak every language fluently or play every instrument perfectly?', '{}', null),
  ('wyr-002', 'Would You Rather', 'Would you rather always know when someone is lying to you, or always get away with lying yourself?', '{}', null),
  ('wyr-003', 'Would You Rather', 'Would you rather have a rewind button for your life or a pause button?', '{}', null),
  ('wyr-004', 'Would You Rather', 'Would you rather lose all your memories from the past 5 years or never be able to make new long-term memories?', '{}', null),
  ('wyr-005', 'Would You Rather', 'Would you rather be famous for something embarrassing or completely unknown despite doing something incredible?', '{}', null),
  ('wyr-006', 'Would You Rather', 'Would you rather always have to say what you''re thinking or never be able to speak again?', '{}', null),
  ('wyr-007', 'Would You Rather', 'Would you rather live in a world without music or a world without movies?', '{}', null),
  ('wyr-008', 'Would You Rather', 'Would you rather be the funniest person in the room or the most intelligent?', '{}', null),
  ('wyr-009', 'Would You Rather', 'Would you rather have the ability to fly or be completely invisible whenever you wanted?', '{}', null),
  ('wyr-010', 'Would You Rather', 'Would you rather know the exact date of your death or the exact cause?', '{}', null),
  ('wiw-001', 'Which Is Worse', 'Which is worse: realizing you''ve been mispronouncing a word for years, or mispronouncing someone''s name in front of a crowd?', '{}', null),
  ('wiw-002', 'Which Is Worse', 'Which is worse: being talked about behind your back or being ignored entirely?', '{}', null),
  ('wiw-003', 'Which Is Worse', 'Which is worse: a slow and unreliable internet connection for the rest of your life, or never being allowed to use headphones again?', '{}', null),
  ('wiw-004', 'Which Is Worse', 'Which is worse: accidentally sending a text to the person you were talking about, or pocket-dialing your boss during a private conversation?', '{}', null),
  ('wiw-005', 'Which Is Worse', 'Which is worse: always arriving 30 minutes late to everything, or always arriving 2 hours early?', '{}', null),
  ('wiw-006', 'Which Is Worse', 'Which is worse: forgetting someone''s name 10 seconds after they tell you, or never remembering birthdays?', '{}', null),
  ('hm-001', 'How Much Would It Take', 'How much would someone have to pay you to give up your phone for an entire year?', '{}', null),
  ('hm-002', 'How Much Would It Take', 'How much would someone have to pay you to eat nothing but fast food for 30 days straight?', '{}', null),
  ('hm-003', 'How Much Would It Take', 'How much would someone have to pay you to shave your head completely bald tomorrow?', '{}', null),
  ('hm-004', 'How Much Would It Take', 'How much would someone have to pay you to quit social media forever?', '{}', null),
  ('hm-005', 'How Much Would It Take', 'How much would someone have to pay you to move to a country where you don''t speak the language for 2 years?', '{}', null),
  ('hm-006', 'How Much Would It Take', 'How much would it take for you to never listen to your favorite music artist again?', '{}', null),
  ('rb-001', 'Rate How Much You Believe', 'Rate how much you believe: everything happens for a reason. (1 = not at all, 3 = absolutely)', '{}', null),
  ('rb-002', 'Rate How Much You Believe', 'Rate how much you believe: people can truly change who they are at their core. (1 = not at all, 3 = absolutely)', '{}', null),
  ('rb-003', 'Rate How Much You Believe', 'Rate how much you believe: there is intelligent life elsewhere in the universe. (1 = not at all, 3 = absolutely)', '{}', null),
  ('rb-004', 'Rate How Much You Believe', 'Rate how much you believe: first impressions are usually accurate. (1 = not at all, 3 = absolutely)', '{}', null),
  ('rb-005', 'Rate How Much You Believe', 'Rate how much you believe: luck plays a bigger role than hard work in most people''s success. (1 = not at all, 3 = absolutely)', '{}', null),
  ('rl-001', 'Rate How Much You Like', 'Rate how much you like being the center of attention at a party. (1 = not at all, 3 = love it)', '{}', null),
  ('rl-002', 'Rate How Much You Like', 'Rate how much you like making big spontaneous decisions. (1 = not at all, 3 = love it)', '{}', null),
  ('rl-003', 'Rate How Much You Like', 'Rate how much you like confrontation when you disagree with someone. (1 = not at all, 3 = love it)', '{}', null),
  ('rl-004', 'Rate How Much You Like', 'Rate how much you like your current daily routine. (1 = not at all, 3 = love it)', '{}', null),
  ('rl-005', 'Rate How Much You Like', 'Rate how much you like surprises. (1 = not at all, 3 = love it)', '{}', null),
  ('hye-001', 'Have You Ever', 'Have you ever completely changed your opinion about someone after a single conversation?', '{}', null),
  ('hye-002', 'Have You Ever', 'Have you ever pretended not to see a notification so you wouldn''t have to respond right away?', '{}', null),
  ('hye-003', 'Have You Ever', 'Have you ever made a big life decision based on a gut feeling alone?', '{}', null),
  ('hye-004', 'Have You Ever', 'Have you ever stayed in a friendship or relationship way longer than you should have?', '{}', null),
  ('hye-005', 'Have You Ever', 'Have you ever taken credit for something you didn''t fully deserve?', '{}', null),
  ('hye-006', 'Have You Ever', 'Have you ever laughed at something you absolutely should not have?', '{}', null),
  ('tat-001', 'Tell About a Time', 'Tell about a time when you had to make a really tough choice between two people.', '{}', null),
  ('tat-002', 'Tell About a Time', 'Tell about a time when something that seemed terrible at the time turned out to be a blessing.', '{}', null),
  ('tat-003', 'Tell About a Time', 'Tell about a time when you felt completely out of your depth but pushed through anyway.', '{}', null),
  ('tat-004', 'Tell About a Time', 'Tell about a time when a stranger unexpectedly made your day significantly better.', '{}', null),
  ('tat-005', 'Tell About a Time', 'Tell about a time when you surprised even yourself.', '{}', null),
  ('wyr-011', 'Would You Rather', 'Which would you rather improve instantly? Physical fitness, Financial situation, Dating life, or Career trajectory.', '{"adults"}', null),
  ('rb-006', 'Rate How Much You Believe', 'Rate how much you believe: Aliens have visited Earth. (1 = not at all, 3 = absolutely)', '{"adults"}', null),
  ('wiw-007', 'Which Is Worse', 'Which is worse financially? Living paycheck to paycheck, Long-term debt, Hating your job but making money, or Missing opportunities out of fear?', '{"adults"}', null),
  ('rl-006', 'Rate How Much You Like', 'Rate how much you like: Fast food at midnight. (1 = not at all, 3 = love it)', '{"adults"}', null),
  ('wyr-012', 'Would You Rather', 'Which would you rather live in? Tiny luxury apartment downtown, Large suburban home, Mountain cabin, or Beachfront condo.', '{"adults"}', null),
  ('rb-007', 'Rate How Much You Believe', 'Rate how much you believe: Governments hide major truths from the public. (1 = not at all, 3 = absolutely)', '{"adults"}', null),
  ('wiw-008', 'Which Is Worse', 'Which is worse socially? Being ignored, Being misunderstood, Being judged, or Being forgotten?', '{"adults"}', null),
  ('rl-007', 'Rate How Much You Like', 'Rate how much you like: Binge-watching shows for hours. (1 = not at all, 3 = love it)', '{"adults"}', null),
  ('wyr-013', 'Would You Rather', 'Which would you rather have long-term? Total financial security, Creative freedom, Maximum free time, or Rapid career growth.', '{"adults"}', null),
  ('rb-008', 'Rate How Much You Believe', 'Rate how much you believe: Prayer changes outcomes. (1 = not at all, 3 = absolutely)', '{"adults"}', null),
  ('wiw-009', 'Which Is Worse', 'Which is worse at work? Micromanagement, No feedback, Office drama, or Repetitive tasks?', '{"adults"}', null),
  ('rl-008', 'Rate How Much You Like', 'Rate how much you like: Wearing sweatpants all day. (1 = not at all, 3 = love it)', '{"adults"}', null),
  ('wyr-014', 'Would You Rather', 'Which would you rather sacrifice for a year? Social media, Streaming shows, Coffee, or Eating out.', '{"adults"}', null),
  ('rb-009', 'Rate How Much You Believe', 'Rate how much you believe: Simulation theory could be true. (1 = not at all, 3 = absolutely)', '{"adults"}', null),
  ('wiw-010', 'Which Is Worse', 'Which is worse in a relationship? Constant small arguments, Emotional distance, Jealousy, or Lack of ambition?', '{"adults"}', null),
  ('rl-009', 'Rate How Much You Like', 'Rate how much you like: Dessert even when full. (1 = not at all, 3 = love it)', '{"adults"}', null),
  ('wyr-015', 'Would You Rather', 'Which would you rather be known for? Intelligence, Kindness, Ambition, or Humor.', '{"adults"}', null),
  ('rb-010', 'Rate How Much You Believe', 'Rate how much you believe: Karma is real. (1 = not at all, 3 = absolutely)', '{"adults"}', null),
  ('wiw-011', 'Which Is Worse', 'Which is worse long-term? Playing it too safe, Taking reckless risks, Changing direction too often, or Never changing?', '{"adults"}', null),
  ('rl-010', 'Rate How Much You Like', 'Rate how much you like: Canceling plans last minute. (1 = not at all, 3 = love it)', '{"adults"}', null),
  ('wyr-016', 'Would You Rather', 'Which would you rather be known as on this cruise? The planner, The entertainer, The peacemaker, or The instigator.', '{"siblings-cruise"}', null),
  ('rl-011', 'Rate How Much You Like', 'Rate how much you like: Cruise buffet round two. (1 = not at all, 3 = love it)', '{"siblings-cruise"}', null),
  ('wiw-012', 'Which Is Worse', 'Which is worse on a cruise? Sunburn, Seasickness, Lost luggage, or No WiFi?', '{"siblings-cruise"}', null),
  ('rb-011', 'Rate How Much You Believe', 'Rate how much you believe: Someone in this family packed way too much. (1 = not at all, 3 = absolutely)', '{"siblings-cruise"}', null),
  ('wyr-017', 'Would You Rather', 'Which would you rather do on sea day? Nap on deck, Play nonstop games, Explore the ship, or Sit and talk for hours.', '{"siblings-cruise"}', null),
  ('wyr-018', 'Would You Rather', 'Which sibling role fits you best? Responsible one, Competitive one, Chill one, or Dramatic one.', '{"siblings-cruise"}', null),
  ('rl-012', 'Rate How Much You Like', 'Rate how much you like: Staying up way too late talking. (1 = not at all, 3 = love it)', '{"siblings-cruise"}', null),
  ('wiw-013', 'Which Is Worse', 'Which is worse in a shared cabin? Snoring, Messy suitcase explosion, Hogging the bathroom, or Thermostat wars?', '{"siblings-cruise"}', null),
  ('wyr-019', 'Would You Rather', 'Which would you rather win? Family game night, Karaoke contest, Trivia challenge, or Ping pong tournament.', '{"siblings-cruise"}', null),
  ('rb-012', 'Rate How Much You Believe', 'Rate how much you believe: Family vacations reveal true personalities. (1 = not at all, 3 = absolutely)', '{"siblings-cruise"}', null),
  ('wyr-020', 'Would You Rather', 'Which would you rather eat every day? Buffet breakfast, Fancy dining room dinner, Poolside burgers, or Room service dessert.', '{"siblings-cruise"}', null),
  ('wiw-014', 'Which Is Worse', 'Which is worse at dinner? Long wait time, Wrong order, Awkward silence, or Someone dominating conversation?', '{"siblings-cruise"}', null),
  ('rl-013', 'Rate How Much You Like', 'Rate how much you like: Trying adventurous foods on vacation. (1 = not at all, 3 = love it)', '{"siblings-cruise"}', null),
  ('wyr-021', 'Would You Rather', 'Which would you rather have? Balcony cabin, Interior cabin with more excursions, Bigger cabin with no window, or Cheapest cabin more spending money.', '{"siblings-cruise"}', null),
  ('wiw-015', 'Which Is Worse', 'Which is worse? Losing your cruise card, Missing the ship at port, Running out of sunscreen, or Sharing one bathroom?', '{"siblings-cruise"}', null),
  ('rb-013', 'Rate How Much You Believe', 'Rate how much you believe: The oldest sibling still acts like the boss. (1 = not at all, 3 = absolutely)', '{"siblings-cruise"}', null),
  ('wyr-022', 'Would You Rather', 'Which would you rather do at port? Beach day, Historical tour, Shopping spree, or Food tour.', '{"siblings-cruise"}', null),
  ('wyr-023', 'Would You Rather', 'Which sibling are you on excursions? Map reader, Photo taker, Complainer, or Wanderer.', '{"siblings-cruise"}', null),
  ('rl-014', 'Rate How Much You Like', 'Rate how much you like: Cruise ship shows. (1 = not at all, 3 = love it)', '{"siblings-cruise"}', null),
  ('wiw-016', 'Which Is Worse', 'Which is worse in family group texts? Too many messages, No responses, Inside jokes you do not get, or Planning debates?', '{"siblings-cruise"}', null),
  ('wyr-024', 'Would You Rather', 'Which would you rather forget? Sunscreen, Phone charger, Formal night clothes, or Boarding documents.', '{"siblings-cruise"}', null),
  ('rb-014', 'Rate How Much You Believe', 'Rate how much you believe: Someone will get overly competitive this week. (1 = not at all, 3 = absolutely)', '{"siblings-cruise"}', null),
  ('wyr-025', 'Would You Rather', 'Which would you rather share? A dessert, A cabin, A secret, or A karaoke duet.', '{"siblings-cruise"}', null),
  ('wiw-017', 'Which Is Worse', 'Which is worse on vacation? Rain, Crowds, Sunburn, or Delays?', '{"siblings-cruise"}', null),
  ('rl-015', 'Rate How Much You Like', 'Rate how much you like: Matching family outfits. (1 = not at all, 3 = love it)', '{"siblings-cruise"}', null),
  ('wyr-026', 'Would You Rather', 'Which would you rather relive? Childhood road trips, High school years, Early marriage years, or Empty nest years.', '{"siblings-cruise"}', null),
  ('wiw-018', 'Which Is Worse', 'Which is worse at family dinners? Political debates, Parenting advice, Story repeating, or Phone distractions?', '{"siblings-cruise"}', null),
  ('rb-015', 'Rate How Much You Believe', 'Rate how much you believe: Cruises are the best kind of vacation. (1 = not at all, 3 = absolutely)', '{"siblings-cruise"}', null),
  ('wyr-027', 'Would You Rather', 'Which would you rather control? Dinner reservations, Daily schedule, Excursion choices, or Game night rules.', '{"siblings-cruise"}', null),
  ('wiw-019', 'Which Is Worse', 'Which is worse in sibling rivalry? Being underestimated, Being compared, Being teased, or Being ignored?', '{"siblings-cruise"}', null),
  ('rl-016', 'Rate How Much You Like', 'Rate how much you like: Late night dessert runs. (1 = not at all, 3 = love it)', '{"siblings-cruise"}', null),
  ('wyr-028', 'Would You Rather', 'Which would you rather give up this cruise? Alcohol, Desserts, Social media, or Pool time.', '{"siblings-cruise"}', null),
  ('wiw-020', 'Which Is Worse', 'Which is worse in a cabin mate? Early riser, Night owl, Loud talker, or Neat freak?', '{"siblings-cruise"}', null),
  ('rb-016', 'Rate How Much You Believe', 'Rate how much you believe: We will laugh about this cruise for years. (1 = not at all, 3 = absolutely)', '{"siblings-cruise"}', null),
  ('wyr-029', 'Would You Rather', 'Which would you rather host? Family devotional, Trivia night, Dance party, or Shore excursion.', '{"siblings-cruise"}', null),
  ('wiw-021', 'Which Is Worse', 'Which is worse? Overplanning, No planning, Overspending, or Overscheduling?', '{"siblings-cruise"}', null),
  ('rl-017', 'Rate How Much You Like', 'Rate how much you like: Poolside naps. (1 = not at all, 3 = love it)', '{"siblings-cruise"}', null),
  ('wyr-030', 'Would You Rather', 'Which would you rather win big at? Ship casino, Family game, Cruise raffle, or Dance contest.', '{"siblings-cruise"}', null),
  ('wiw-022', 'Which Is Worse', 'Which is worse? Sunburn peel, Motion sickness meds, Lost sunglasses, or Towel shortage?', '{"siblings-cruise"}', null),
  ('rb-017', 'Rate How Much You Believe', 'Rate how much you believe: Family is more fun as adults than as kids. (1 = not at all, 3 = absolutely)', '{"siblings-cruise"}', null),
  ('wyr-031', 'Would You Rather', 'Which would you rather lead? Morning workout group, Evening board games, Excursion planning, or Dessert tasting.', '{"siblings-cruise"}', null),
  ('wiw-023', 'Which Is Worse', 'Which is worse? Being hangry, Being tired, Being sunburned, or Being bored?', '{"siblings-cruise"}', null),
  ('rl-018', 'Rate How Much You Like', 'Rate how much you like: Taking way too many photos. (1 = not at all, 3 = love it)', '{"siblings-cruise"}', null),
  ('wyr-032', 'Would You Rather', 'Which would you rather argue about? Politics, Sports, Parenting, or Travel plans.', '{"siblings-cruise"}', null),
  ('wiw-024', 'Which Is Worse', 'Which is worse? Missing sunrise, Missing sunset, Missing dinner, or Missing dessert?', '{"siblings-cruise"}', null),
  ('rb-018', 'Rate How Much You Believe', 'Rate how much you believe: Sibling bonds get stronger with age. (1 = not at all, 3 = absolutely)', '{"siblings-cruise"}', null),
  ('wyr-033', 'Would You Rather', 'Which would you rather repeat next year? Same cruise, Different cruise, Road trip, or All inclusive resort.', '{"siblings-cruise"}', null),
  ('wiw-025', 'Which Is Worse', 'Which is worse? Quiet tension, Loud disagreement, Passive aggression, or Competitive trash talk?', '{"siblings-cruise"}', null),
  ('rl-019', 'Rate How Much You Like', 'Rate how much you like: Being unplugged from real life for a week. (1 = not at all, 3 = love it)', '{"siblings-cruise"}', null),
  ('wyr-034', 'Would You Rather', 'Which would you rather remember most from this trip? The laughs, The conversations, The adventures, or The food.', '{"siblings-cruise"}', null),
  ('wyr-035', 'Would You Rather', 'Which would you rather have more of at this stage of life? Time, Energy, Money, or Patience.', '{"seniors-cruise"}', null),
  ('rl-020', 'Rate How Much You Like', 'Rate how much you like: Afternoon naps. (1 = not at all, 3 = love it)', '{"seniors-cruise"}', null),
  ('wiw-026', 'Which Is Worse', 'Which is worse on a cruise? Sunburn, Motion sickness, Waiting in long lines, or Forgetting where you parked your walker?', '{"seniors-cruise"}', null),
  ('rb-019', 'Rate How Much You Believe', 'Rate how much you believe: Life gets better with age. (1 = not at all, 3 = absolutely)', '{"seniors-cruise"}', null),
  ('wyr-036', 'Would You Rather', 'Which would you rather relive for one week? Your 20s, Your 40s, When your children were young, or Right now.', '{"seniors-cruise"}', null),
  ('wiw-027', 'Which Is Worse', 'Which is worse? Being too busy, Being bored, Being overlooked, or Being overcommitted?', '{"seniors-cruise"}', null),
  ('rl-021', 'Rate How Much You Like', 'Rate how much you like: Talking about the good old days. (1 = not at all, 3 = love it)', '{"seniors-cruise"}', null),
  ('wyr-037', 'Would You Rather', 'Which would you rather improve instantly? Memory, Flexibility, Financial security, or Golf game.', '{"seniors-cruise"}', null),
  ('wiw-028', 'Which Is Worse', 'Which is worse at this stage of life? Regret, Missed opportunity, Physical pain, or Losing independence?', '{"seniors-cruise"}', null),
  ('rb-020', 'Rate How Much You Believe', 'Rate how much you believe: Family matters more than career success. (1 = not at all, 3 = absolutely)', '{"seniors-cruise"}', null),
  ('wyr-038', 'Would You Rather', 'Which would you rather spend on? Travel, Grandchildren, Home improvements, or Experiences with friends.', '{"seniors-cruise"}', null),
  ('wiw-029', 'Which Is Worse', 'Which is worse on vacation? Poor service, Loud neighbors, Uncomfortable bed, or Too much walking?', '{"seniors-cruise"}', null),
  ('rl-022', 'Rate How Much You Like', 'Rate how much you like: Early morning quiet time. (1 = not at all, 3 = love it)', '{"seniors-cruise"}', null),
  ('wyr-039', 'Would You Rather', 'Which would you rather give up? Television, Dessert, Driving, or Social media.', '{"seniors-cruise"}', null),
  ('wiw-030', 'Which Is Worse', 'Which is worse? Being underestimated, Being patronized, Being ignored, or Being over helped?', '{"seniors-cruise"}', null),
  ('rb-021', 'Rate How Much You Believe', 'Rate how much you believe: Wisdom comes mostly from experience. (1 = not at all, 3 = absolutely)', '{"seniors-cruise"}', null),
  ('wyr-040', 'Would You Rather', 'Which would you rather do on a cruise? Historical tour, Scenic bus ride, Relax by the pool, or Sit and visit.', '{"seniors-cruise"}', null),
  ('wiw-031', 'Which Is Worse', 'Which is worse in retirement? Too much routine, No routine, Financial stress, or Health concerns?', '{"seniors-cruise"}', null),
  ('rl-023', 'Rate How Much You Like', 'Rate how much you like: Trying new foods. (1 = not at all, 3 = love it)', '{"seniors-cruise"}', null),
  ('wyr-041', 'Would You Rather', 'Which would you rather be known for? Kindness, Reliability, Humor, or Strength.', '{"seniors-cruise"}', null),
  ('wiw-032', 'Which Is Worse', 'Which is worse? Technology confusion, Forgetting names, Hearing loss, or Reading glasses everywhere?', '{"seniors-cruise"}', null),
  ('rb-022', 'Rate How Much You Believe', 'Rate how much you believe: It is never too late to learn something new. (1 = not at all, 3 = absolutely)', '{"seniors-cruise"}', null),
  ('wyr-042', 'Would You Rather', 'Which would you rather prioritize? Health, Travel, Family time, or Community service.', '{"seniors-cruise"}', null),
  ('wiw-033', 'Which Is Worse', 'Which is worse socially? Small talk, Political debates, Loud restaurants, or Being left out?', '{"seniors-cruise"}', null),
  ('rl-024', 'Rate How Much You Like', 'Rate how much you like: Cruises as a vacation choice. (1 = not at all, 3 = love it)', '{"seniors-cruise"}', null),
  ('wyr-043', 'Would You Rather', 'Which would you rather improve? Balance, Stamina, Patience, or Sleep quality.', '{"seniors-cruise"}', null),
  ('wiw-034', 'Which Is Worse', 'Which is worse? Living far from family, Living too close to family, Downsizing, or Maintaining a large home?', '{"seniors-cruise"}', null),
  ('rb-023', 'Rate How Much You Believe', 'Rate how much you believe: Grandchildren keep you young. (1 = not at all, 3 = absolutely)', '{"seniors-cruise"}', null),
  ('wyr-044', 'Would You Rather', 'Which would you rather repeat? A favorite trip from the past, A major life milestone, A simple family gathering, or This exact cruise.', '{"seniors-cruise"}', null),
  ('wiw-035', 'Which Is Worse', 'Which is worse at dinner? Long wait, Loud music, Small portions, or Overly large portions?', '{"seniors-cruise"}', null),
  ('rl-025', 'Rate How Much You Like', 'Rate how much you like: Having a predictable routine. (1 = not at all, 3 = love it)', '{"seniors-cruise"}', null),
  ('wyr-045', 'Would You Rather', 'Which would you rather give advice on? Marriage, Parenting, Finances, or Faith.', '{"seniors-cruise"}', null),
  ('wiw-036', 'Which Is Worse', 'Which is worse? Losing your keys, Losing your phone, Losing your glasses, or Losing your patience?', '{"seniors-cruise"}', null),
  ('rb-024', 'Rate How Much You Believe', 'Rate how much you believe: Attitude shapes aging. (1 = not at all, 3 = absolutely)', '{"seniors-cruise"}', null),
  ('wyr-046', 'Would You Rather', 'Which would you rather host? Family dinner, Game night, Holiday gathering, or Travel reunion.', '{"seniors-cruise"}', null),
  ('wiw-037', 'Which Is Worse', 'Which is worse? Being too cautious, Being too trusting, Being too stubborn, or Being too quiet?', '{"seniors-cruise"}', null),
  ('rl-026', 'Rate How Much You Like', 'Rate how much you like: Watching sunsets. (1 = not at all, 3 = love it)', '{"seniors-cruise"}', null),
  ('wyr-047', 'Would You Rather', 'Which would you rather strengthen? Body, Mind, Faith, or Friendships.', '{"seniors-cruise"}', null),
  ('wiw-038', 'Which Is Worse', 'Which is worse? Financial uncertainty, Health uncertainty, Family conflict, or Loneliness?', '{"seniors-cruise"}', null),
  ('rb-025', 'Rate How Much You Believe', 'Rate how much you believe: The best years can still be ahead. (1 = not at all, 3 = absolutely)', '{"seniors-cruise"}', null),
  ('wyr-048', 'Would You Rather', 'Which would you rather spend more time doing? Serving others, Traveling, Learning, or Relaxing.', '{"seniors-cruise"}', null),
  ('wiw-039', 'Which Is Worse', 'Which is worse? Too much quiet, Too much noise, Too much change, or Too much sameness?', '{"seniors-cruise"}', null),
  ('rl-027', 'Rate How Much You Like', 'Rate how much you like: Sharing life stories. (1 = not at all, 3 = love it)', '{"seniors-cruise"}', null),
  ('wyr-049', 'Would You Rather', 'Which would you rather simplify? Finances, Schedule, Possessions, or Responsibilities.', '{"seniors-cruise"}', null),
  ('wiw-040', 'Which Is Worse', 'Which is worse? Being too independent, Relying on others, Asking for help, or Not asking for help?', '{"seniors-cruise"}', null),
  ('rb-026', 'Rate How Much You Believe', 'Rate how much you believe: Gratitude improves happiness. (1 = not at all, 3 = absolutely)', '{"seniors-cruise"}', null),
  ('wyr-050', 'Would You Rather', 'Which would you rather keep? Mobility, Memory, Independence, or Close relationships.', '{"seniors-cruise"}', null),
  ('wiw-041', 'Which Is Worse', 'Which is worse? A long day, A long week, A long winter, or A long silence?', '{"seniors-cruise"}', null),
  ('rl-028', 'Rate How Much You Like', 'Rate how much you like: Being off the grid for a few days. (1 = not at all, 3 = love it)', '{"seniors-cruise"}', null),
  ('wyr-051', 'Would You Rather', 'Which would you rather be remembered for? Faith, Love, Integrity, or Service.', '{"seniors-cruise"}', null),
  ('wyr-052', 'Would You Rather', 'Which would you rather have? A pet dragon, A pet dinosaur, A pet unicorn, or A pet monkey.', '{"kids"}', null),
  ('rl-029', 'Rate How Much You Like', 'Rate how much you like: Pizza night. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wiw-042', 'Which Is Worse', 'Which is worse? Dropping your ice cream, Losing your favorite toy, Skipping recess, or Going to bed early?', '{"kids"}', null),
  ('rb-027', 'Rate How Much You Believe', 'Rate how much you believe: Aliens could be real. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-053', 'Would You Rather', 'Which would you rather be? Superhero, Famous athlete, Scientist, or YouTuber.', '{"kids"}', null),
  ('wiw-043', 'Which Is Worse', 'Which is worse at school? Too much homework, Pop quiz, Forgetting your lunch, or Being late?', '{"kids"}', null),
  ('rl-030', 'Rate How Much You Like', 'Rate how much you like: Staying up past bedtime. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wyr-054', 'Would You Rather', 'Which would you rather explore? Jungle, Space, Deep ocean, or Ancient pyramid.', '{"kids"}', null),
  ('wiw-044', 'Which Is Worse', 'Which is worse? Wet socks, Sticky hands, Loud noise, or No snacks?', '{"kids"}', null),
  ('rb-028', 'Rate How Much You Believe', 'Rate how much you believe: Magic could be real. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-055', 'Would You Rather', 'Which would you rather eat every day? Tacos, Burgers, Mac and cheese, or Pancakes.', '{"kids"}', null),
  ('wiw-045', 'Which Is Worse', 'Which is worse? Sharing your dessert, Sharing your room, Sharing your toys, or Sharing your screen time?', '{"kids"}', null),
  ('rl-031', 'Rate How Much You Like', 'Rate how much you like: Playing outside. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wyr-056', 'Would You Rather', 'Which would you rather build? Treehouse, Robot, Giant LEGO set, or Go kart.', '{"kids"}', null),
  ('wiw-046', 'Which Is Worse', 'Which is worse? Rain on play day, Hot weather, Cold weather, or Windy day?', '{"kids"}', null),
  ('rb-029', 'Rate How Much You Believe', 'Rate how much you believe: Dinosaurs would be awesome to see. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-057', 'Would You Rather', 'Which would you rather win? Big trophy, Free toys, One hundred dollar gift card, or Pizza party.', '{"kids"}', null),
  ('wiw-047', 'Which Is Worse', 'Which is worse? Losing a game, Getting teased, Falling down, or Getting grounded?', '{"kids"}', null),
  ('rl-032', 'Rate How Much You Like', 'Rate how much you like: Ice cream. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wyr-058', 'Would You Rather', 'Which would you rather ride? Roller coaster, Waterslide, Zipline, or Go kart.', '{"kids"}', null),
  ('wiw-048', 'Which Is Worse', 'Which is worse? Boring day, Busy day, Tired day, or Hungry day?', '{"kids"}', null),
  ('rb-030', 'Rate How Much You Believe', 'Rate how much you believe: Superheroes could exist. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-059', 'Would You Rather', 'Which would you rather have as a superpower? Fly, Turn invisible, Super strength, or Talk to animals.', '{"kids"}', null),
  ('wiw-049', 'Which Is Worse', 'Which is worse? No WiFi, No TV, No candy, or No friends?', '{"kids"}', null),
  ('rl-033', 'Rate How Much You Like', 'Rate how much you like: Video games. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wyr-060', 'Would You Rather', 'Which would you rather collect? Sports cards, Comics, Rocks and gems, or Stickers.', '{"kids"}', null),
  ('wiw-050', 'Which Is Worse', 'Which is worse? Too much homework, Too many chores, Too much noise, or Too much waiting?', '{"kids"}', null),
  ('rb-031', 'Rate How Much You Believe', 'Rate how much you believe: Wishes can come true. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-061', 'Would You Rather', 'Which would you rather have? Big birthday party, Big vacation, Big pile of presents, or Big cake.', '{"kids"}', null),
  ('wiw-051', 'Which Is Worse', 'Which is worse? Losing your backpack, Losing your phone, Losing your seat, or Losing your snack?', '{"kids"}', null),
  ('rl-034', 'Rate How Much You Like', 'Rate how much you like: Sleepovers. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wyr-062', 'Would You Rather', 'Which would you rather try? Surfing, Skateboarding, Snowboarding, or Rock climbing.', '{"kids"}', null),
  ('wiw-052', 'Which Is Worse', 'Which is worse? Missing dessert, Missing recess, Missing movie night, or Missing practice?', '{"kids"}', null),
  ('rb-032', 'Rate How Much You Believe', 'Rate how much you believe: Treasure maps could be real. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-063', 'Would You Rather', 'Which would you rather invent? Flying car, Robot helper, Time machine, or Video game.', '{"kids"}', null),
  ('wiw-053', 'Which Is Worse', 'Which is worse? Loud thunder, Dark room, Big wave, or No flashlight?', '{"kids"}', null),
  ('rl-035', 'Rate How Much You Like', 'Rate how much you like: Telling jokes. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wyr-064', 'Would You Rather', 'Which would you rather be famous for? Sports, Singing, Science, or Being funny.', '{"kids"}', null),
  ('wiw-054', 'Which Is Worse', 'Which is worse? Being last picked, Not winning, Spilling your drink, or Getting messy?', '{"kids"}', null),
  ('rb-033', 'Rate How Much You Believe', 'Rate how much you believe: There might be hidden treasure somewhere. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-065', 'Would You Rather', 'Which would you rather learn? Magic tricks, Coding, Guitar, or Cooking.', '{"kids"}', null),
  ('wiw-055', 'Which Is Worse', 'Which is worse? Long car rides, Long lines, Long lectures, or Long chores?', '{"kids"}', null),
  ('rl-036', 'Rate How Much You Like', 'Rate how much you like: Adventure. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wyr-066', 'Would You Rather', 'Which would you rather have? Secret clubhouse, Secret password, Secret hideout, or Secret handshake.', '{"kids"}', null),
  ('wiw-056', 'Which Is Worse', 'Which is worse? Losing at a game, Not getting picked, Dropping food, or Forgetting sunscreen?', '{"kids"}', null),
  ('rb-034', 'Rate How Much You Believe', 'Rate how much you believe: Bigfoot could exist. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-067', 'Would You Rather', 'Which would you rather eat first? Dessert, Fries, Fruit, or Nuggets.', '{"kids"}', null),
  ('wiw-057', 'Which Is Worse', 'Which is worse? Wet clothes, Muddy shoes, Sunburn, or Mosquito bites?', '{"kids"}', null),
  ('rl-037', 'Rate How Much You Like', 'Rate how much you like: Summer vacation. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wyr-068', 'Would You Rather', 'Which would you rather remember most about being a kid? Playing outside, Family time, Friends, or Fun adventures.', '{"kids"}', null),
  ('wyr-069', 'Would You Rather', 'Which would you rather have? A robot helper, A magic wand, A jetpack, or A talking dog.', '{"kids"}', null),
  ('rl-038', 'Rate How Much You Like', 'Rate how much you like: Snow days. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wiw-058', 'Which Is Worse', 'Which is worse? Stepping in mud, Spilling your drink, Dropping your snack, or Forgetting your homework?', '{"kids"}', null),
  ('rb-035', 'Rate How Much You Believe', 'Rate how much you believe: There could be treasure hidden somewhere near you. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-070', 'Would You Rather', 'Which would you rather explore? Haunted house, Space station, Underwater city, or Giant jungle.', '{"kids"}', null),
  ('wiw-059', 'Which Is Worse', 'Which is worse? Losing a race, Missing your turn, Being last picked, or Tripping in public?', '{"kids"}', null),
  ('rl-039', 'Rate How Much You Like', 'Rate how much you like: Playing board games. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wyr-071', 'Would You Rather', 'Which would you rather invent? New candy, Flying skateboard, Homework machine, or Super shoes.', '{"kids"}', null),
  ('wiw-060', 'Which Is Worse', 'Which is worse? Long homework, Long car ride, Long speech, or Long line?', '{"kids"}', null),
  ('rb-036', 'Rate How Much You Believe', 'Rate how much you believe: Dragons would be awesome to see. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-072', 'Would You Rather', 'Which would you rather eat for a week? Only pizza, Only pancakes, Only tacos, or Only burgers.', '{"kids"}', null),
  ('wiw-061', 'Which Is Worse', 'Which is worse? Getting wet in the rain, Getting sweaty, Getting sandy, or Getting sticky?', '{"kids"}', null),
  ('rl-040', 'Rate How Much You Like', 'Rate how much you like: Playing sports. (1 = not at all, 3 = love it)', '{"kids"}', null),
  ('wyr-073', 'Would You Rather', 'Which would you rather ride? Giant swing, Roller coaster, Water slide, or Ferris wheel.', '{"kids"}', null),
  ('wiw-062', 'Which Is Worse', 'Which is worse? No dessert, No recess, No TV, or No phone time?', '{"kids"}', null),
  ('rb-037', 'Rate How Much You Believe', 'Rate how much you believe: Superpowers could be real someday. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-074', 'Would You Rather', 'Which would you rather build? Fort in the living room, LEGO city, Treehouse, or Race car.', '{"kids"}', null),
  ('wiw-063', 'Which Is Worse', 'Which is worse? Losing your hat, Losing your backpack, Losing your favorite shirt, or Losing your snack?', '{"kids"}', null),
  ('wyr-075', 'Would You Rather', 'Which would you rather learn? Karate, Magic tricks, Coding, or Baking.', '{"kids"}', null),
  ('wiw-064', 'Which Is Worse', 'Which is worse? Getting teased, Getting ignored, Getting blamed, or Getting embarrassed?', '{"kids"}', null),
  ('rb-038', 'Rate How Much You Believe', 'Rate how much you believe: Wishes sometimes come true. (1 = not at all, 3 = absolutely)', '{"kids"}', null),
  ('wyr-076', 'Would You Rather', 'Which would you rather have for a birthday? Giant cake, Big party, Lots of presents, or Surprise trip.', '{"kids"}', null),
  ('wiw-065', 'Which Is Worse', 'Which is worse? Loud thunder, Dark hallway, Big spider, or Cold shower?', '{"kids"}', null),
  ('wyr-077', 'Would You Rather', 'Which would you rather have? Spaghetti hair, Marshmallow toes, Popcorn hands, or Jelly knees.', '{"kids-silly"}', null),
  ('rl-041', 'Rate How Much You Like', 'Rate how much you like: Making weird noises for no reason. (1 = not at all, 3 = love it)', '{"kids-silly"}', null),
  ('wiw-066', 'Which Is Worse', 'Which is worse? Burping during a speech, Sneezing during a photo, Hiccupping in class, or Laughing at the wrong time?', '{"kids-silly"}', null),
  ('rb-039', 'Rate How Much You Believe', 'Rate how much you believe: Somewhere a chicken is smarter than a human. (1 = not at all, 3 = absolutely)', '{"kids-silly"}', null),
  ('wyr-078', 'Would You Rather', 'Which would you rather ride to school? Giant hamster, Flying pizza, Invisible skateboard, or Rocket powered scooter.', '{"kids-silly"}', null),
  ('wiw-067', 'Which Is Worse', 'Which is worse? Sitting on a whoopee cushion, Walking into a glass door, Waving back at someone who was not waving, or Calling the teacher Mom?', '{"kids-silly"}', null),
  ('rl-042', 'Rate How Much You Like', 'Rate how much you like: Talking in silly accents. (1 = not at all, 3 = love it)', '{"kids-silly"}', null),
  ('wyr-079', 'Would You Rather', 'Which would you rather sneeze? Glitter, Confetti, Bubbles, or Tiny rubber ducks.', '{"kids-silly"}', null),
  ('wiw-068', 'Which Is Worse', 'Which is worse? Wearing pajamas to school, Shoes on the wrong feet, Backwards shirt all day, or Mismatched socks forever?', '{"kids-silly"}', null),
  ('rb-040', 'Rate How Much You Believe', 'Rate how much you believe: Socks disappear because they teleport. (1 = not at all, 3 = absolutely)', '{"kids-silly"}', null),
  ('wyr-080', 'Would You Rather', 'Which would you rather eat? Chocolate covered pickles, Spicy ice cream, Broccoli candy, or Ketchup cereal.', '{"kids-silly"}', null),
  ('wiw-069', 'Which Is Worse', 'Which is worse? Slipping on a banana peel, Getting slimed, Stepping in gum, or Dropping your lunch tray?', '{"kids-silly"}', null),
  ('rl-043', 'Rate How Much You Like', 'Rate how much you like: Belly laughs that will not stop. (1 = not at all, 3 = love it)', '{"kids-silly"}', null),
  ('wyr-081', 'Would You Rather', 'Which would you rather be for a day? Giant baby, Tiny adult, Talking dog, or Dancing robot.', '{"kids-silly"}', null),
  ('wiw-070', 'Which Is Worse', 'Which is worse? Toothpaste on your nose, Toilet paper on your shoe, Hair sticking straight up, or Spinach in your teeth?', '{"kids-silly"}', null),
  ('rb-041', 'Rate How Much You Believe', 'Rate how much you believe: Monkeys would be great teachers. (1 = not at all, 3 = absolutely)', '{"kids-silly"}', null),
  ('wyr-082', 'Would You Rather', 'Which would you rather have? Super loud hiccups, Super squeaky voice, Super slow walk, or Super fast blinking.', '{"kids-silly"}', null),
  ('wiw-071', 'Which Is Worse', 'Which is worse? Getting tickled too long, Getting hugged too tight, Getting spun too fast, or Getting splashed unexpectedly?', '{"kids-silly"}', null),
  ('rl-044', 'Rate How Much You Like', 'Rate how much you like: Dancing like nobody is watching. (1 = not at all, 3 = love it)', '{"kids-silly"}', null),
  ('wyr-083', 'Would You Rather', 'Which would you rather invent? Homework eating robot, Sock finder machine, Self making bed, or Talking backpack.', '{"kids-silly"}', null),
  ('wiw-072', 'Which Is Worse', 'Which is worse? Thinking it is Saturday but it is Monday, Dreaming pizza then waking hungry, Dropping your last cookie, or Losing rock paper scissors?', '{"kids-silly"}', null),
  ('rb-042', 'Rate How Much You Believe', 'Rate how much you believe: Aliens might look like jellybeans. (1 = not at all, 3 = absolutely)', '{"kids-silly"}', null),
  ('wyr-084', 'Would You Rather', 'Which would you rather have stuck to your hand? Honey, Glue, Peanut butter, or Slime.', '{"kids-silly"}', null),
  ('wiw-073', 'Which Is Worse', 'Which is worse? Random loud sneeze, Random loud stomach growl, Random loud yawn, or Random loud giggle?', '{"kids-silly"}', null),
  ('rl-045', 'Rate How Much You Like', 'Rate how much you like: Acting completely ridiculous. (1 = not at all, 3 = love it)', '{"kids-silly"}', null),
  ('wyr-085', 'Would You Rather', 'Which would you rather have for hair? Noodles, Cotton candy, Spaghetti, or Grass.', '{"kids-silly"}', null),
  ('rl-046', 'Rate How Much You Like', 'Rate how much you like: Making up ridiculous songs. (1 = not at all, 3 = love it)', '{"kids-silly"}', null),
  ('wiw-074', 'Which Is Worse', 'Which is worse? Saying you too to the waiter, Liking an old photo, Voice crack, or Trying to be cool and failing?', '{"kids-silly"}', null),
  ('rb-043', 'Rate How Much You Believe', 'Rate how much you believe: Cats secretly judge everyone. (1 = not at all, 3 = absolutely)', '{"kids-silly"}', null),
  ('wyr-086', 'Would You Rather', 'Which would you rather sneeze out? Glitter, Balloons, Frog sounds, or Confetti.', '{"kids-silly"}', null),
  ('wiw-075', 'Which Is Worse', 'Which is worse? Shoelace never stays tied, Sleeves always wet, Socks always slide down, or Backpack zipper stuck?', '{"kids-silly"}', null),
  ('rl-047', 'Rate How Much You Like', 'Rate how much you like: Telling the same joke five times. (1 = not at all, 3 = love it)', '{"kids-silly"}', null),
  ('wyr-087', 'Would You Rather', 'Which would you rather have as a pet? Tiny dinosaur, Grumpy hamster, Dramatic parrot, or Super polite snake.', '{"kids-silly"}', null),
  ('wiw-076', 'Which Is Worse', 'Which is worse? Water on your pants, Falling while running, Wrong name, or Laughing at a serious moment?', '{"kids-silly"}', null),
  ('rb-044', 'Rate How Much You Believe', 'Rate how much you believe: Aliens might be scared of humans. (1 = not at all, 3 = absolutely)', '{"kids-silly"}', null),
  ('wyr-088', 'Would You Rather', 'Which would you rather eat? Pickle popsicle, Chocolate pizza, Sour spaghetti, or Rainbow broccoli.', '{"kids-silly"}', null),
  ('wiw-077', 'Which Is Worse', 'Which is worse? Forever itchy nose, Forever tickly foot, Forever hiccup, or Forever sneeze coming?', '{"kids-silly"}', null),
  ('rl-048', 'Rate How Much You Like', 'Rate how much you like: Making silly faces in photos. (1 = not at all, 3 = love it)', '{"kids-silly"}', null),
  ('wyr-089', 'Would You Rather', 'Which would you rather ride to the store? Shopping cart with jets, Giant bouncy ball, Sleepy turtle, or Flying couch.', '{"kids-silly"}', null),
  ('wiw-078', 'Which Is Worse', 'Which is worse? Accidentally shouting, Accidentally whispering, Accidentally singing, or Accidentally snorting?', '{"kids-silly"}', null),
  ('rb-045', 'Rate How Much You Believe', 'Rate how much you believe: Socks disappear into another universe. (1 = not at all, 3 = absolutely)', '{"kids-silly"}', null),
  ('wyr-090', 'Would You Rather', 'Which would you rather have stuck on your hand? Syrup, Peanut butter, Slime, or Sticker goo.', '{"kids-silly"}', null),
  ('wiw-079', 'Which Is Worse', 'Which is worse? Stepping on a LEGO, Ketchup on white shirt, Biting your tongue, or Laughing soda out your nose?', '{"kids-silly"}', null),
  ('rl-049', 'Rate How Much You Like', 'Rate how much you like: Laughing so hard your stomach hurts. (1 = not at all, 3 = love it)', '{"kids-silly"}', null),
  ('wyr-091', 'Would You Rather', 'Which would you rather be for a day? Talking backpack, Superhero chicken, Ninja librarian, or Dancing vacuum.', '{"kids-silly"}', null),
  ('wiw-080', 'Which Is Worse', 'Which is worse? Laugh sounds like a donkey, Sneeze sounds like a trumpet, Yawn sounds like a roar, or Burp sounds like a tuba?', '{"kids-silly"}', null),
  ('rb-046', 'Rate How Much You Believe', 'Rate how much you believe: Fish have secrets. (1 = not at all, 3 = absolutely)', '{"kids-silly"}', null),
  ('wyr-092', 'Would You Rather', 'Which would you rather wear to school? A cape, Clown shoes, Superhero mask, or Fancy top hat.', '{"kids-silly"}', null),
  ('wiw-081', 'Which Is Worse', 'Which is worse? Autocorrect to banana, Backpack squeaks loudly, Chair makes funny noises, or Pencil squeals?', '{"kids-silly"}', null),
  ('rl-050', 'Rate How Much You Like', 'Rate how much you like: Doing something just because. (1 = not at all, 3 = love it)', '{"kids-silly"}', null),
  ('op-001', 'Your Opinion', 'School is mostly... Fun, Hard, Boring, or Exciting?', '{"kids"}', null),
  ('op-002', 'Your Opinion', 'Recess should be... Longer, More organized, Free play, or Sports focused?', '{"kids"}', null),
  ('op-003', 'Your Opinion', 'Homework is... Important, Annoying, Too much, or Helpful?', '{"kids"}', null),
  ('op-004', 'Your Opinion', 'The best subject is... Math, Science, Reading, or Art?', '{"kids"}', null),
  ('op-005', 'Your Opinion', 'Friends should be... Kind, Funny, Loyal, or Honest?', '{"kids"}', null),
  ('op-006', 'Your Opinion', 'Being brave means... Trying new things, Standing up for others, Not giving up, or Speaking up?', '{"kids"}', null),
  ('op-007', 'Your Opinion', 'The best birthday is... Big party, Family dinner, Trip somewhere, or Lots of presents?', '{"kids"}', null),
  ('op-008', 'Your Opinion', 'Summer is better than... Winter, Spring, Fall, or School year?', '{"kids"}', null),
  ('op-009', 'Your Opinion', 'Video games are... Fun, Addictive, Challenging, or Creative?', '{"kids"}', null),
  ('op-010', 'Your Opinion', 'Sports are best when... Winning, Trying hard, Having fun, or Playing with friends?', '{"kids"}', null),
  ('op-011', 'Your Opinion', 'Reading is... Adventurous, Relaxing, Boring, or Important?', '{"kids"}', null),
  ('op-012', 'Your Opinion', 'Being a leader means... Helping others, Being in charge, Setting an example, or Listening?', '{"kids"}', null),
  ('op-013', 'Your Opinion', 'The best pet is... Dog, Cat, Fish, or Hamster?', '{"kids"}', null),
  ('op-014', 'Your Opinion', 'Learning should be... Fun, Challenging, Creative, or Hands on?', '{"kids"}', null),
  ('op-015', 'Your Opinion', 'Family time is... Fun, Important, Sometimes loud, or Special?', '{"kids"}', null),
  ('op-016', 'Your Opinion', 'The best snack is... Sweet, Salty, Healthy, or Crunchy?', '{"kids"}', null),
  ('op-017', 'Your Opinion', 'Being kind is... Powerful, Easy, Important, or Hard sometimes?', '{"kids"}', null),
  ('op-018', 'Your Opinion', 'The best way to spend a weekend is... Outside, With friends, With family, or Relaxing?', '{"kids"}', null),
  ('op-019', 'Your Opinion', 'Trying new things is... Scary, Exciting, Important, or Hard?', '{"kids"}', null),
  ('op-020', 'Your Opinion', 'The best movie is... Funny, Action packed, Animated, or Adventure?', '{"kids"}', null),
  ('op-021', 'Your Opinion', 'Winning feels... Awesome, Good but not everything, Important, or Exciting?', '{"kids"}', null),
  ('op-022', 'Your Opinion', 'Being different is... Cool, Hard, Normal, or Special?', '{"kids"}', null),
  ('op-023', 'Your Opinion', 'School projects are best when... Creative, Group based, Short, or Hands on?', '{"kids"}', null),
  ('op-024', 'Your Opinion', 'The best holiday is... Christmas, Halloween, Birthday, or Fourth of July?', '{"kids"}', null),
  ('op-025', 'Your Opinion', 'The best superpower would be... Flying, Invisibility, Super strength, or Talking to animals?', '{"kids"}', null),
  ('op-026', 'Your Opinion', 'Chores are... Necessary, Annoying, Good practice, or Unfair?', '{"kids"}', null),
  ('op-027', 'Your Opinion', 'Adventure means... Exploring outside, Trying something new, Traveling, or Playing games?', '{"kids"}', null),
  ('op-028', 'Your Opinion', 'Being smart means... Knowing facts, Asking questions, Trying hard, or Helping others learn?', '{"kids"}', null),
  ('op-029', 'Your Opinion', 'The best teacher is... Funny, Strict, Kind, or Creative?', '{"kids"}', null),
  ('op-030', 'Your Opinion', 'The best way to solve arguments is... Talking it out, Walking away, Apologizing, or Getting help?', '{"kids"}', null),
  ('op-031', 'Your Opinion', 'Creativity is... Drawing, Building, Imagining, or Problem solving?', '{"kids"}', null),
  ('op-032', 'Your Opinion', 'Teamwork works best when... Everyone tries, Everyone listens, There is a leader, or It is organized?', '{"kids"}', null),
  ('op-033', 'Your Opinion', 'Confidence comes from... Practice, Support, Success, or Trying?', '{"kids"}', null),
  ('op-034', 'Your Opinion', 'The best day ever includes... Friends, Family, Fun, or Surprises?', '{"kids"}', null),
  ('op-035', 'Your Opinion', 'Learning from mistakes is... Important, Hard, Embarrassing, or Helpful?', '{"kids"}', null),
  ('op-036', 'Your Opinion', 'The best game is... Fast paced, Strategy based, Silly, or Team based?', '{"kids"}', null),
  ('op-037', 'Your Opinion', 'Being responsible means... Doing chores, Finishing homework, Helping others, or Keeping promises?', '{"kids"}', null),
  ('op-038', 'Your Opinion', 'The coolest invention would be... Flying car, Robot helper, Time machine, or Teleport machine?', '{"kids"}', null),
  ('op-039', 'Your Opinion', 'Being honest is... Brave, Important, Hard sometimes, or Always right?', '{"kids"}', null),
  ('op-040', 'Your Opinion', 'The best vacation is... Beach, Mountains, Theme park, or Camping?', '{"kids"}', null),
  ('op-041', 'Your Opinion', 'Music is best when it is... Loud, Happy, Calm, or Fast?', '{"kids"}', null),
  ('op-042', 'Your Opinion', 'The best lunch is... Packed lunch, School lunch, Fast food, or Homemade?', '{"kids"}', null),
  ('op-043', 'Your Opinion', 'Helping others feels... Good, Important, Rewarding, or Nice?', '{"kids"}', null),
  ('op-044', 'Your Opinion', 'The best school day is... Field trip, Game day, Short day, or Party day?', '{"kids"}', null),
  ('op-045', 'Your Opinion', 'Being curious means... Asking questions, Exploring, Reading, or Experimenting?', '{"kids"}', null),
  ('op-046', 'Your Opinion', 'The best season is... Summer, Winter, Spring, or Fall?', '{"kids"}', null),
  ('op-047', 'Your Opinion', 'Imagination is... Powerful, Fun, Creative, or Limitless?', '{"kids"}', null),
  ('op-048', 'Your Opinion', 'The best way to relax is... Watching TV, Playing outside, Reading, or Talking?', '{"kids"}', null),
  ('op-049', 'Your Opinion', 'Friendship means... Trust, Loyalty, Fun, or Support?', '{"kids"}', null),
  ('op-050', 'Your Opinion', 'The best thing about being a kid is... Freedom, Fun, Energy, or Imagination?', '{"kids"}', null),
  ('op-051', 'Your Opinion', 'The best animal to be for a day is... Monkey, Shark, Eagle, or Penguin?', '{"kids-silly"}', null),
  ('op-052', 'Your Opinion', 'The funniest sound is... Burp, Boing, Quack, or Squeak?', '{"kids-silly"}', null),
  ('op-053', 'Your Opinion', 'If food could talk it would be... Complaining, Singing, Giving advice, or Telling secrets?', '{"kids-silly"}', null),
  ('op-054', 'Your Opinion', 'The best thing to wear on your head is... Crown, Pirate hat, Superhero mask, or Giant sombrero?', '{"kids-silly"}', null),
  ('op-055', 'Your Opinion', 'If socks disappear they go to... Another universe, A sock party, A monster closet, or A washing machine portal?', '{"kids-silly"}', null),
  ('op-056', 'Your Opinion', 'The best way to travel is... Rocket, Unicorn, Roller skates, or Teleporting?', '{"kids-silly"}', null),
  ('op-057', 'Your Opinion', 'The best silly walk is... Robot walk, Chicken walk, Slow motion walk, or Bouncy walk?', '{"kids-silly"}', null),
  ('op-058', 'Your Opinion', 'The funniest vegetable is... Broccoli, Carrot, Corn, or Pickle?', '{"kids-silly"}', null),
  ('op-059', 'Your Opinion', 'If your backpack could talk it would... Complain, Sing, Joke, or Whisper secrets?', '{"kids-silly"}', null),
  ('op-060', 'Your Opinion', 'The best superpower for a chicken is... Flying lasers, Super speed, Invisibility, or Talking?', '{"kids-silly"}', null),
  ('op-061', 'Your Opinion', 'The best weird hair is... Cotton candy hair, Spaghetti hair, Rainbow hair, or Grass hair?', '{"kids-silly"}', null),
  ('op-062', 'Your Opinion', 'The silliest pet is... Tiny dinosaur, Dancing hamster, Singing parrot, or Polite snake?', '{"kids-silly"}', null),
  ('op-063', 'Your Opinion', 'If pencils had personalities they would be... Dramatic, Serious, Funny, or Sleepy?', '{"kids-silly"}', null),
  ('op-064', 'Your Opinion', 'The best thing to sneeze is... Glitter, Bubbles, Confetti, or Rubber ducks?', '{"kids-silly"}', null),
  ('op-065', 'Your Opinion', 'The funniest dance move is... Flossing, Chicken dance, Robot spin, or Jump and wiggle?', '{"kids-silly"}', null),
  ('op-066', 'Your Opinion', 'If homework disappeared it would... Hide, Run away, Explode, or Turn into candy?', '{"kids-silly"}', null),
  ('op-067', 'Your Opinion', 'The best silly voice is... Squeaky, Deep monster, Robot, or Whispery spy?', '{"kids-silly"}', null),
  ('op-068', 'Your Opinion', 'The best imaginary friend would be... Invisible ninja, Talking donut, Giant hamster, or Mini superhero?', '{"kids-silly"}', null),
  ('op-069', 'Your Opinion', 'If chairs made sounds they would... Boing, Squeak, Honk, or Roar?', '{"kids-silly"}', null),
  ('op-070', 'Your Opinion', 'The best weird food is... Chocolate pizza, Pickle ice cream, Ketchup cereal, or Broccoli candy?', '{"kids-silly"}', null),
  ('op-071', 'Your Opinion', 'If animals ran school the principal would be... Lion, Owl, Monkey, or Elephant?', '{"kids-silly"}', null),
  ('op-072', 'Your Opinion', 'The best silly costume is... Banana suit, Superhero cape, Clown outfit, or Giant duck suit?', '{"kids-silly"}', null),
  ('op-073', 'Your Opinion', 'The funniest weather is... Rain of candy, Snow of marshmallows, Wind of bubbles, or Clouds of glitter?', '{"kids-silly"}', null),
  ('op-074', 'Your Opinion', 'If your shoes had powers they would... Fly, Jump super high, Run super fast, or Turn invisible?', '{"kids-silly"}', null),
  ('op-075', 'Your Opinion', 'The best silly invention is... Sock finder machine, Homework eating robot, Self tying shoes, or Talking sandwich?', '{"kids-silly"}', null),
  ('op-076', 'Your Opinion', 'If trees could talk they would... Tell jokes, Give advice, Sing songs, or Complain about squirrels?', '{"kids-silly"}', null),
  ('op-077', 'Your Opinion', 'The best laugh sounds like... Goat, Robot, Trumpet, or Donkey?', '{"kids-silly"}', null),
  ('op-078', 'Your Opinion', 'The best silly holiday is... Opposite day, Pajama day, Crazy hat day, or Backwards day?', '{"kids-silly"}', null),
  ('op-079', 'Your Opinion', 'If you could turn into food you would be... Pizza, Ice cream, Donut, or Spaghetti?', '{"kids-silly"}', null),
  ('op-080', 'Your Opinion', 'The best animal teacher would be... Monkey, Owl, Dog, or Penguin?', '{"kids-silly"}', null),
  ('op-081', 'Your Opinion', 'If slime had feelings it would be... Happy, Sleepy, Mischievous, or Grumpy?', '{"kids-silly"}', null),
  ('op-082', 'Your Opinion', 'The best silly game is... Freeze dance, Tag, Hide and seek, or Sock toss?', '{"kids-silly"}', null),
  ('op-083', 'Your Opinion', 'If robots ruled the world they would... Organize everything, Dance nonstop, Make homework harder, or Make candy free?', '{"kids-silly"}', null),
  ('op-084', 'Your Opinion', 'The best silly hat is... Top hat with feathers, Giant foam finger, Pirate hat, or Spinning propeller hat?', '{"kids-silly"}', null),
  ('op-085', 'Your Opinion', 'If your bed could move it would... Bounce, Roll, Fly, or Spin?', '{"kids-silly"}', null),
  ('op-086', 'Your Opinion', 'The best silly noise is... Boop, Meep, Quack, or Honk?', '{"kids-silly"}', null),
  ('op-087', 'Your Opinion', 'If candy could run it would... Race, Hide, Jump, or Fly?', '{"kids-silly"}', null),
  ('op-088', 'Your Opinion', 'The best silly pet trick is... Backflip, Sing, Talk, or Dance?', '{"kids-silly"}', null),
  ('op-089', 'Your Opinion', 'If bananas had jobs they would be... Comedians, Teachers, Athletes, or Singers?', '{"kids-silly"}', null),
  ('op-090', 'Your Opinion', 'The best silly superpower is... Stretchy arms, Big ears, Super tickle, or Super giggle?', '{"kids-silly"}', null),
  ('op-091', 'Your Opinion', 'If clouds were food they would be... Cotton candy, Popcorn, Marshmallows, or Pancakes?', '{"kids-silly"}', null),
  ('op-092', 'Your Opinion', 'The best silly sound effect is... Zap, Boing, Splat, or Zoom?', '{"kids-silly"}', null),
  ('op-093', 'Your Opinion', 'If your shadow could talk it would... Copy you, Tease you, Sing, or Give advice?', '{"kids-silly"}', null),
  ('op-094', 'Your Opinion', 'The best silly parade float is... Giant duck, Candy castle, Robot dragon, or Jumping pizza?', '{"kids-silly"}', null),
  ('op-095', 'Your Opinion', 'If frogs ran the news they would... Ribbit headlines, Splash stories, Jump interviews, or Sing weather reports?', '{"kids-silly"}', null),
  ('op-096', 'Your Opinion', 'The best silly dance party theme is... Pajamas, Superheroes, Animals, or Aliens?', '{"kids-silly"}', null),
  ('op-097', 'Your Opinion', 'If your lunchbox had powers it would... Teleport food, Refill snacks, Keep secrets, or Sing songs?', '{"kids-silly"}', null),
  ('op-098', 'Your Opinion', 'The best silly superhero name is... Captain Giggle, Professor Zoom, Doctor Bounce, or Major Meep?', '{"kids-silly"}', null),
  ('op-099', 'Your Opinion', 'If crayons ruled the world it would be... Colorful, Messy, Creative, or Chaotic?', '{"kids-silly"}', null),
  ('op-100', 'Your Opinion', 'The best silly ending to a story is... Everyone laughs, It was all a dream, A giant dance party, or A talking banana appears?', '{"kids-silly"}', null),
  ('wyr-093', 'Would You Rather', 'Which would you rather adjust mid-meeting? Agenda, Technology setup, Group participation, or Time schedule.', '{"work-conference"}', null),
  ('wyr-094', 'Would You Rather', 'Which would you rather rely on most? Preparation, Experience, Team support, or Improvisation.', '{"work-conference"}', null),
  ('wyr-095', 'Would You Rather', 'Which would you rather fix first? Confusing instructions, Slow systems, Outdated materials, or Lack of training.', '{"work-conference"}', null),
  ('wyr-096', 'Would You Rather', 'Which would you rather bring to a new assignment? Technical expertise, Organization skills, Teaching ability, or Relationship building.', '{"work-conference"}', null),
  ('wyr-097', 'Would You Rather', 'Which would you rather do when something fails? Troubleshoot immediately, Ask for help, Restart everything, or Move on and revisit later.', '{"work-conference"}', null),
  ('wyr-098', 'Would You Rather', 'Which would you rather have during a presentation? Perfect slides, Clear speaking, Engaged audience, or Strong message.', '{"work-conference"}', null),
  ('wyr-099', 'Would You Rather', 'Which would you rather manage? A detailed plan, A flexible plan, A small team, or A large team.', '{"work-conference"}', null),
  ('wyr-100', 'Would You Rather', 'Which would you rather improve in meetings? Clarity, Speed, Participation, or Outcomes.', '{"work-conference"}', null),
  ('wyr-101', 'Would You Rather', 'Which would you rather receive? Clear direction, Full trust, Frequent feedback, or Independence.', '{"work-conference"}', null),
  ('wyr-102', 'Would You Rather', 'Which would you rather focus on? Short-term needs, Long-term goals, Immediate fixes, or Future prevention.', '{"work-conference"}', null),
  ('wiw-082', 'Which Is Worse', 'Which is worse? Too many emails, Too many messages, Too many meetings, or Too many tasks?', '{"work-conference"}', null),
  ('wiw-083', 'Which Is Worse', 'Which is worse? Unclear expectations, Changing expectations, No expectations, or Unrealistic expectations?', '{"work-conference"}', null),
  ('wiw-084', 'Which Is Worse', 'Which is worse? Working alone too much, Working in groups too much, Too much structure, or Too little structure?', '{"work-conference"}', null),
  ('wiw-085', 'Which Is Worse', 'Which is worse? Not enough time, Not enough help, Not enough information, or Not enough tools?', '{"work-conference"}', null),
  ('wiw-086', 'Which Is Worse', 'Which is worse? Overplanning, Underplanning, Overcommunicating, or Undercommunicating?', '{"work-conference"}', null),
  ('wiw-087', 'Which Is Worse', 'Which is worse? Too much detail, Too little detail, Too many options, or Too few options?', '{"work-conference"}', null),
  ('wiw-088', 'Which Is Worse', 'Which is worse? Waiting for approval, Acting without approval, Delayed decisions, or No decisions?', '{"work-conference"}', null),
  ('rl-051', 'Rate How Much You Like', 'Rate how much you like learning by doing (1 = not at all, 3 = love it)', '{"work-conference"}', null),
  ('rl-052', 'Rate How Much You Like', 'Rate how much you like structured training (1 = not at all, 3 = love it)', '{"work-conference"}', null),
  ('rl-053', 'Rate How Much You Like', 'Rate how much you like solving unexpected problems (1 = not at all, 3 = love it)', '{"work-conference"}', null),
  ('rl-054', 'Rate How Much You Like', 'Rate how much you like working with new people (1 = not at all, 3 = love it)', '{"work-conference"}', null),
  ('op-101', 'Your Opinion', 'What is your opinion on meetings? Keep them short and frequent, Fewer but longer meetings, Only when needed, or Replace with messages?', '{"work-conference"}', null),
  ('op-102', 'Your Opinion', 'What is your opinion on training others? Essential responsibility, Important but secondary, Helpful when needed, or Not my role?', '{"work-conference"}', null),
  ('op-103', 'Your Opinion', 'What is your opinion on using new tools? Adopt quickly, Adopt carefully, Wait and see, or Avoid unless required?', '{"work-conference"}', null),
  ('op-104', 'Your Opinion', 'What is your opinion on handling challenges? Address immediately, Plan before acting, Collaborate first, or Wait for guidance?', '{"work-conference"}', null),
  ('wyr-103', 'Would You Rather', 'Which would you rather present at? Small training (10 people), Medium group (50), Large conference (200+), or Record a video instead.', '{"adults"}', null),
  ('wyr-104', 'Would You Rather', 'Which would you rather troubleshoot? Wi-Fi not working, Login/account issues, Projector won’t connect, or Audio/microphone problems.', '{"adults"}', null),
  ('wyr-105', 'Would You Rather', 'Which would you rather travel with? Only carry-on, One checked bag, Two full suitcases, or Someone else handles it.', '{"adults"}', null),
  ('wyr-106', 'Would You Rather', 'Which would you rather do on a free evening at conference? Explore the city, Rest at hotel, Visit with others, or Catch up on work.', '{"adults"}', null),
  ('wyr-107', 'Would You Rather', 'Which would you rather improve most in your calling? Training others, Technical skills, Organization, or Communication.', '{"adults"}', null),
  ('wyr-108', 'Would You Rather', 'Which would you rather eat for a week? Food from your home country, Food from the host country, American-style food, or A mix of everything.', '{"adults"}', null),
  ('wyr-109', 'Would You Rather', 'Which would you rather be known for? Always reliable, Highly skilled, Great teacher, or Great leader.', '{"adults"}', null),
  ('wyr-110', 'Would You Rather', 'Which would you rather deal with? Slow internet, Outdated equipment, Limited budget, or Not enough volunteers.', '{"adults"}', null),
  ('wyr-111', 'Would You Rather', 'Which would you rather attend? Hands-on workshop, Inspirational talk, Panel discussion, or Small group discussion.', '{"adults"}', null),
  ('wyr-112', 'Would You Rather', 'Which would you rather have? More time, More people helping, Better tools, or Clearer direction.', '{"adults"}', null),
  ('wiw-089', 'Which Is Worse', 'Which is worse during a presentation? Slides don’t load, Internet goes out, Microphone fails, or Time runs out?', '{"adults"}', null),
  ('wiw-090', 'Which Is Worse', 'Which is worse when traveling? Lost luggage, Delayed flight, Jet lag, or Language barrier?', '{"adults"}', null),
  ('wiw-091', 'Which Is Worse', 'Which is worse in a meeting? Too long, No clear purpose, No decisions made, or Too many opinions?', '{"adults"}', null),
  ('wiw-092', 'Which Is Worse', 'Which is worse in a project? Last-minute changes, Lack of direction, Limited resources, or Tight deadlines?', '{"adults"}', null),
  ('wiw-093', 'Which Is Worse', 'Which is worse at church? Tech not working, Last-minute requests, Not enough help, or Miscommunication?', '{"adults"}', null),
  ('wiw-094', 'Which Is Worse', 'Which is worse personally? Being late, Being unprepared, Forgetting something important, or Not understanding instructions?', '{"adults"}', null),
  ('wiw-095', 'Which Is Worse', 'Which is worse at a conference? Too much sitting, Too much talking, Too little interaction, or Too packed schedule?', '{"adults"}', null),
  ('rl-055', 'Rate How Much You Like', 'Rate how much you like trying food from other countries (1 = not at all, 3 = love it)', '{"adults"}', null),
  ('rl-056', 'Rate How Much You Like', 'Rate how much you like working with people from different cultures (1 = not at all, 3 = love it)', '{"adults"}', null),
  ('rl-057', 'Rate How Much You Like', 'Rate how much you like learning new technology tools (1 = not at all, 3 = love it)', '{"adults"}', null),
  ('rl-058', 'Rate How Much You Like', 'Rate how much you like speaking or presenting in front of others (1 = not at all, 3 = love it)', '{"adults"}', null),
  ('op-105', 'Your Opinion', 'What is your opinion on best way to learn new tech skills? Formal training, Self-study, Learning from others, or Hands-on experience?', '{"adults"}', null),
  ('op-106', 'Your Opinion', 'What is your opinion on best way to support local leaders? Provide training, Provide tools, Provide ongoing support, or Step back and let them lead?', '{"adults"}', null),
  ('op-107', 'Your Opinion', 'What is your opinion on best use of limited resources? Improve infrastructure, Train people, Simplify systems, or Focus on key priorities?', '{"adults"}', null),
  ('op-108', 'Your Opinion', 'What is your opinion on best part of gatherings like this? Learning new ideas, Meeting people, Feeling unity, or Gaining inspiration?', '{"adults"}', null)
on conflict (id) do nothing;

commit;
